stages:
  - build_test
  - build_image


build_test:
  image: maven:3.8.4-jdk-11
  stage: build_test
  script:
    - mvn clean package


build_image:
  image: docker:20.10.7                
  services:
    - docker:20.10.7-dind             
  variables:
    DOCKER_TLS_CERTDIR: "/certs"      
  stage: build_image                   
  before_script:
    - echo "$docker_passwd"

  script:
    - docker build -t gitlab-java-app .   
    - docker push gitlab-java-app         
